### ISSUE TITLE
Add NPM package

### ISSUE THREAD

**Issue by rfoel** [Kinark/Materialize-stepper#11]
I think it would be nice to have a NPM package, way easier to work with.

**Comment by Kinark** [comment]
I'll probably add it soon, I'm going to have some help too :)

I'll keep this issue open until NPM integration is done.

**Comment by rfoel** [comment]
@Kinark Great. I'd still use SASS instead of CSS. I'd be happy to help if needed.

**Comment by bastianwegge** [comment]
@rfoel feel free to make a PR for SASS integration. I think we can somehow talk @Kinark into using it ;)

**Comment by Kinark** [comment]
@TetianaP PR merged! NPM package is already avaible :)
