### ISSUE TITLE
Create Meteor package

### ISSUE THREAD

**Issue by TristanWiley** [Kinark/Materialize-stepper#15]
Create a Meteor package and add to https://atmospherejs.com/

I'll try to get around to this eventually, but I unfortunately don't have a lot of time.

**Comment by Kinark** [comment]
I don't see the benefit of using the meteor package. Why did you add your github repository in that PR?

**Comment by TristanWiley** [comment]
Oops, totally forgot to change it back to your repo. A meteor package makes it a lot easier for usage in Meteor projects since I had issues using the NPM package.

**Comment by afifsohaili** [comment]
What issues do you have? I'm using it fine on my Meteor project.

**Comment by codexcokexcook** [comment]
it keeps showing 'Uncaught SyntaxError: Unexpected token <' and the steppers can't be loaded
![screen shot 2018-03-08 at 2 46 54 pm](https://user-images.githubusercontent.com/32152882/37137169-9955afd4-22df-11e8-9724-23acad538901.png)

seems couldn't locate the stepper css and js file.

**Comment by Kinark** [comment]
Since this is issue is an year old and creataing a Meteor package is not in the plans, I'm closing this issue for now.
