### ISSUE TITLE
Fields are not validated when skipping steps using non-linear stepper

### ISSUE THREAD

**Issue by KimNorgaard** [Kinark/Materialize-stepper#17]
Hi,

Thank you for a great plugin :)

I'm not sure if this is a bug or if I am missing something.

If I make a non-linear stepper with field validation (e.g. with a required field) but I choose to skip directly to the last step and submit the form, I would expect:

- the form to be invalid
- the first step with invalid fields to be activated
- all steps with errors marked as invalid
- the errors to be shown

However, the form just submits as if there are not errors.

I cloned your codepen playground, removed 'linear' from the stepper and changed the final button to a submit button, also removing the callback.

https://codepen.io/anon/pen/bRKJoX

Is this by design? If so, do you have any suggestions as to how I can achieve the desired behavior?

**Comment by KimNorgaard** [comment]
Add a PR that works for my use case. If it looks good I can update documentation, version, and minify the javascript.

$.fn.submitStepper should probably also be modified to support the validation.

**Comment by Kinark** [comment]
So, the function of non-linear steppers is to allow users to move freely between steps, from step 1 to step 5, for example. Lets suppose you add required attribute in all fields of step 2 and 3, but not on steps 1 and 4. The user could jump to the final step (4) without having to fill the required inputs in 2 and 3.

The logic I could see is, for example, some tests that check the inputs in the steps before of the step you want to jump to and then allow or not the freely move between steps. 

This would be some kind of semi-linear stepper, but it would be a whole new feature. For now, I recommend to use linear stepper instead and remove required attributes from the inputs you don't want to be obligatory. 

I mean, in the example I mentioned above, where there's a 4 stepped stepper with required inputs only on 2 and 3, it would work exactly like the linear stepper.

**Comment by KimNorgaard** [comment]
Thanks for the reply.

The form I'm implementing has a lot of fields. That is why I choose a wizard/stepper in the first place. However, most fields have sane defaults and users would often skip to the last steps and submit. Other times they will go back and forth between steps until everything is filled out and then submit.

I think your suggestion of making a semi-linear stepper would be acceptable, but I also still think the best behavior when submitting a form in the non-linear mode would be to validate the whole form and give indication of errors. That is, after all, the expected behavior of forms in general.

The PR I submitted gets you this behavior without sacrificing anything.

**Comment by Kinark** [comment]
The new MStepper was rewritten from scratch, so this doesn't apply anymore.
I'll be closing this issue for now.
Feel free to reopen it anytime you want.
