### ISSUE TITLE
conflict with use strict

### ISSUE THREAD

**Issue by Badlapje** [Kinark/Materialize-stepper#20]
Because you use a lot of implicit global variable declarations (declaring a new var without using the var/let/const keywords) your script breaks if it is imported into a js script that declares "use strict" at the top.  

Declaring all variables explicitly (good practice anyways) solves this issue.  I've gone ahead and created a pull request with just that fix: #19

**Comment by Kinark** [comment]
Fixed by merging you PR. Thank you :)
