### ISSUE TITLE
How to stop responsiveness of linear stepper in latest version

### ISSUE THREAD

**Issue by rdFixFellows** [Kinark/Materialize-stepper#22]
How can I stop responsiveness of linear stepper in latest version

**Comment by Kinark** [comment]
You mean the horizontal stepper turning to vertical in small screens?
Unfortuntately that's not possible. But there is no way for the horizontal stepper to look good in small screens, so...
You mean the vertical stepper turning to horizontal in big screens?
Just remove the class `horizontal` from the `stepper` tag.
