### ISSUE TITLE
stepper skipping steps on linear stepper

### ISSUE THREAD

**Issue by jwp528** [Kinark/Materialize-stepper#27]
Hey there,
Love the stepper, but i've noticed an issue where on a linear stepper where step 1 has required fields and step 3 has required fields, but step 2 is optional. the continue button skips the second step. 

adding it here in case it is an issue but i'm hoping i've just missed something

**Comment by Kinark** [comment]
Unfortunately I couldn't reproduce the bug. Take a look:
https://codepen.io/Kinark/pen/QOdVOg
It looks fine.
Could you post your code, a codepen or something?

**Comment by jwp528** [comment]
Hey all,
Sorry for the late response. I combed through what I had and couldn't figure out for the life of me what was going wrong, so I decided to nuke what I had and just rebuild from scratch, the stepper is now functioning properly as intended. Thanks for the response!
