### ISSUE TITLE
Disable jquery validation

### ISSUE THREAD

**Issue by Vishal0203** [Kinark/Materialize-stepper#3]
Is there a way i can disable jquery validation, that comes by default with the library?

**Comment by Kinark** [comment]
For now, nope. jQuery validate plugin is the only way to make required inputs "requireble". But you can remove "required" attribute from your inputs.

I'll make a non-jQueryValidate version soon, but it won't allow you to validate your inputs (what means that people will be able to proceed without filling them.

The upside is that jQuery Validate library is small (just 22kb minified), so... For now, the only solution is to include it and remove required attributes (sorry :c).

Thank you :)

**Comment by Kinark** [comment]
Done! jQueryValidationPlugin is now totally optional (version 2.0.1).
