### ISSUE TITLE
 Error using the next button

### ISSUE THREAD

**Issue by HerlyOlivares** [Kinark/Materialize-stepper#31]
Hi, when you go to the last button, it remains in the preload and in the chrome console it shows me the following error:

materialize-stepper.min.js: 5 Uncaught TypeError: Can not read property 'call' of undefined

It happens the same in the example of your web: https://kinark.github.io/Materialize-stepper/

it does not happen using the superior controls

![image](https://user-images.githubusercontent.com/14128168/33375636-f5893d2c-d4e0-11e7-9b9a-501ce4f6ea9a.png)

**Comment by Kinark** [comment]
Sorry, didn't get what exactly is your problem.
The preloader screen only happens when you are calling some feedback function.
Are you using it?

**Comment by Kinark** [comment]
Since there was no answer, I'll close it to keep the issues clean. Feel free to reopen it anytime.
