### ISSUE TITLE
Angular Support

### ISSUE THREAD

**Issue by austrolex** [Kinark/Materialize-stepper#32]
I am using MaterializeCSS together with Angular. Is there any way to add the stepper? I can't seem to figure out how...

**Comment by judasane** [comment]
Same here.

**Comment by Kinark** [comment]
Unfortunately this project doesn't have any plans to add support to Angular framework. I consider React, but not Angular, so I'm closing this issue.

**Comment by Kinark** [comment]
Since there was no answer, I'll close it to keep the issues clean. Feel free to reopen it anytime.

**Comment by ermarkar** [comment]
Any support or way to use with angular till now?

**Comment by ermarkar** [comment]
This is how I make it working with Angular

In **angular.json** file

`"node_modules/materialize-stepper/dist/css/mstepper.css"`

in scripts property.

And in styles property

`"node_modules/materialize-stepper/dist/js/mstepper.js"`

Then in ts file import like
`declare const MStepper: any;`

https://stackoverflow.com/questions/56738035/how-to-use-materialize-stepper-with-angular/56739012#56739012
