### ISSUE TITLE
Go back to first step from last step

### ISSUE THREAD

**Issue by surazzarus** [Kinark/Materialize-stepper#33]
I am trying to go to first step to edit from the last step, so I have a link to do so.
After I click the link I am using

`$('.stepper').openStep(1, callback);`

But I am not sure what to do with this callback. If I don't put this callback, it goes to step 1 and comes back again to the same step.

Thank you

**Comment by Kinark** [comment]
Fixed, among with anothor thousand fixes. Everything was made from scratch in the new beta version. 
The new version changes the whole API, so I believe you won't have any more troubles.
Check the new [docs](https://kinark.github.io/Materialize-stepper/) to learn more.
