### ISSUE TITLE
Minified javascript file doesn't contain parallel stepper code

### ISSUE THREAD

**Issue by feclist** [Kinark/Materialize-stepper#34]
As the title says :). When you download the compressed archive from the provided link the minified javascript file has the old code. The normal javascript file is fine though.

**Comment by Kinark** [comment]
Unfortunately the parallel stepper was removed due to a major update.  Everything was made from scratch in the new beta version. Check the new [docs](https://kinark.github.io/Materialize-stepper/) to learn more.
