### ISSUE TITLE
Create Bower Package

### ISSUE THREAD

**Issue by alisonmoura** [Kinark/Materialize-stepper#35]
I'd like to download the package using bower. And now I don't have much time to improve the project by myself, so it's why I'm creating this issue. Thanks for the package though. It's REALLY good!!! 😄

**Comment by Kinark** [comment]
This will be considered in a near future since the project is alive again. Meanwhile, I'll leave this one open. Be sure to check the new [docs](https://kinark.github.io/Materialize-stepper/).

**Comment by Kinark** [comment]
There's a message in Bower's homepage for years that say:
> ...psst! While Bower is maintained, we recommend using Yarn and Webpack or Parcel for front-end projects read how to migrate!
So since Bower is a kinda abandoned project, there's no plan to add the package in their repository anymore.

**Comment by alisonmoura** [comment]
Thanks for you reply! I think that the most part of packages there was in the Bower's domain are moving or will be moving to NPM's dependency or Yarn exclusively. But is great enough that this package is in the NPM and Yarn!
