### ISSUE TITLE
Addistional Validation

### ISSUE THREAD

**Issue by anish137i** [Kinark/Materialize-stepper#38]
i might doing something wrong, but in stepper if we add validate class for text input and i want to validate that input with min and alfa numeric only. and prevent user to continue. but as default validate class only work if only single word is typed and add class valid in that input how i can add the custom methods. or mobile or unique number validation with visual error feedback before continue.

**Comment by Loxyz** [comment]
Hey,
it works to me if i'm using "$.validator.addMethod" in my own JS.
Can you show any code ?

**Comment by Kinark** [comment]
Fixed, among with anothor thousand fixes. Everything was made from scratch in the new beta version. Check the new [docs](https://kinark.github.io/Materialize-stepper/) to learn more.
