### ISSUE TITLE
Key press Enter in inputs go back steps in stepper horizontal.

### ISSUE THREAD

**Issue by AngelTrinidad** [Kinark/Materialize-stepper#39]
How can I deactivate it?

**Comment by Kinark** [comment]
Since there was no answer, I'll be closing this issue for now.
Feel free to reopen it anytime you want.

**Comment by kieraneglin** [comment]
This was happening to me as well with a vertical stepper. To anyone else who comes across this, I resolved it by ensuring all buttons (except the submit button) had an explicit type attribute set to `button`
