### ISSUE TITLE
Materlize Collapsible is not working well |   height is over flowing

### ISSUE THREAD

**Issue by atul-ui-developer** [Kinark/Materialize-stepper#43]
![skyzon infotech e service portal 1](https://user-images.githubusercontent.com/6805996/40410274-6c731f80-5e7e-11e8-82c3-75461a5af01a.png)
![skyzon infotech e service portal](https://user-images.githubusercontent.com/6805996/40410275-6ca40e06-5e7e-11e8-89b1-2529c52c7120.png)

**Comment by atul-ui-developer** [comment]
Please help me to fix the collpasible menu issue  ...height is not detecting on clicking collapsible

**Comment by Kinark** [comment]
Sorry for the late answer. Everything was made from scratch in the new beta version. Could you test it agian with the information in the new [docs](https://kinark.github.io/Materialize-stepper/)?

**Comment by Kinark** [comment]
Since there was no answer, I'll close it to keep the issues clean. Feel free to reopen it anytime.
