### ISSUE TITLE
Compatibility issues with Materialize CSS 1.0.0 and jQuery 3.3.1

### ISSUE THREAD

**Issue by Qwabhina** [Kinark/Materialize-stepper#44]
I'm looking to add Materialize Stepper in my project, but it seems not to work with the prerequisites [materializecss v1.0.0, jquery v3.3.1] I added. But the same files are working on the other pages without the Materialize Stepper.

**Comment by mvanorder** [comment]
I tested with Materialize 1.0.0-rc.1 and jQuery 3.3.1 where it would render but now move to the next step.  In the console I was receiving the error: `TypeError: w.easing[this.easing] is not a function`.  There's a comment on Issue #40 [Here](https://github.com/Kinark/Materialize-stepper/issues/40#issuecomment-385488161) showing how to correct this.

**Comment by Kinark** [comment]
Sorry everyone, I'm updating everything in a new version I'm working on. Check the updated [README](https://github.com/Kinark/Materialize-stepper/blob/master/README.md) for more information.

Thanks and sorry again.

**Comment by Kinark** [comment]
Fixed, among with anothor thousand fixes. Everything was made from scratch in the new beta version. Check the new [docs](https://kinark.github.io/Materialize-stepper/) to learn more.
