### ISSUE TITLE
Not working with new Materializecss versions without jquery

### ISSUE THREAD

**Issue by judasane** [Kinark/Materialize-stepper#45]
The new Materialize versions allows to use the framework without JQuery.

It is a shame that we cannot use this stepper that way

**Comment by SwaroopH** [comment]
This has little do with Materialize itself as this stepper requires jQuery as a dependency. I was able to get it to work with the new framework without much trouble. Give it a try!

**Comment by marcialsoto** [comment]
Can you please elaborate the solution? 
I am trying: 

var materializeStepper = require("materialize-stepper")

And receiving a error message:

Uncaught ReferenceError: $ is not defined
at Object.require.materialize-stepper (vendor.js:153102)

**Comment by SwaroopH** [comment]
You aren't including jQuery which is a dependency for stepper.

**Comment by agrorural** [comment]
Yes i am:

const $ = require('jquery');
require('materialize-css');
var materializeStepper = require("materialize-stepper");

I am using Browserify + Gulp.

Thanks for your time, buddy.

**Comment by SwaroopH** [comment]
Will have to look at that later but try directly linking (or CDNs) in the html for now? @agrorural @marcialsoto

**Comment by agrorural** [comment]
Same output.

Using: https://www.jsdelivr.com/package/npm/materialize-stepper

**Comment by Kinark** [comment]
Sorry everyone, I'm updating everything in a new version I'm working on. See the updated [README](https://github.com/Kinark/Materialize-stepper/blob/master/README.md) for mor information.

Thanks and sorry again.

**Comment by Kinark** [comment]
Fixed, among with anothor thousand fixes. Everything was made from scratch in the new beta version. Check the new [docs](https://kinark.github.io/Materialize-stepper/) to learn more.
