### ISSUE TITLE
Responsive horizontal stepper

### ISSUE THREAD

**Issue by friek108** [Kinark/Materialize-stepper#5]
It would be great to have the horizontal css stepper as responsive, or breaks on to a new line for smaller screens.. (like flex display) when it reaches it's container size..

**Comment by Kinark** [comment]
Working on it :)

**Comment by Kinark** [comment]
Finally done u.u
Now, in version 2.1 it turns vertical from 992px (width) down.

RESPONSIVE STEPPER, YAY!!!

Sorry for taking so long ;-;
