### ISSUE TITLE
Validation function callback

### ISSUE THREAD

**Issue by roiLeo** [Kinark/Materialize-stepper#50]
Hi,
Thanks for the update.
I've find something wrong with the validation function.
When it return true it should proceed and when I'm returning false it should show error but it does the opposite.
Here is my codepen: https://codepen.io/roileo/pen/KradYB?editors=1010
One other thing, is there any way to display which field got the required attribute ? (browser tooltip)

**Comment by Kinark** [comment]
Indeed, it should proceed if the validation functions returns true. 
In the line 244 in [one of the recent commits] (https://github.com/Kinark/Materialize-stepper/commit/b6a53b6517b7d0d708fa3704cab3839f53f37eda#diff-d2b0a72e2da8b4714de34de6b3e557dc) I forgot to add a `!` to invert the check. 

Gonna fix it as soon as possible. I need to make some tests to avoid mistakes like this.

And yeah, it's possible to show the browser tooltip in the required inputs with functions like [reportValidity](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/reportValidity), but it's a feature that I didn't implement yet.

But I believe it's possible to use the validation function with the mentioned method and achieve what you want even in the current state (without the feature).

**Comment by Kinark** [comment]
Fixed on the last release.
