### ISSUE TITLE
Can't add steps in the end of stepper

### ISSUE THREAD

**Issue by Kinark** [Kinark/Materialize-stepper#54]
It's not possible to add steps at the end of the stepper.

The function `activateStep()` use steps that currently are in the index you want as a reference to add the new steps before it. Since there's no step after the last one, you can't add a step to the end of the stepper.

This is an issue already related in #53, but reopened here since the former was to relate another bug. This one is specific.

**Comment by jasonglisson** [comment]
Thanks for setting this up as a new issue. I'm going to probably look into a workaround for this today. Any tips on a good starting point?

**Comment by jasonglisson** [comment]
FYI....it looks like my workaround of using a hidden step is working so that I can have a single step and add one to it.
