### ISSUE TITLE
doc for nextStep(), prevStep() and openStep()

### ISSUE THREAD

**Issue by HIRANO-Satoshi** [Kinark/Materialize-stepper#56]
The source comment says nextStep() has three params. 

The current doc says just nextStep(cb) and no explanation about cb.

**Comment by Kinark** [comment]
`cb` is a known term in dev world, it means "callback".
Since it's a common thing and a simple google search for "cb in javascript" results in the explanation, I believe there's no need for documenting this.

Closing to keep issues clean.
Feel free to reopen it anytime you want to add more points.
