### ISSUE TITLE
stepchange event

### ISSUE THREAD

**Issue by brianpkelley** [Kinark/Materialize-stepper#60]
I noticed the `stepchange` event was not being fired when clicking on title linkes.

Moving/adding "stepper.dispatchEvent(events.STEPCHANGE);" from `openStep`, `nextStep`, `prevStep` and into `_openAction` fixed the issue.

**Comment by Kinark** [comment]
This is a pretty smart solution, it's really stupid of me not to put it on the global `_openAction` method lol
Thank you!
I'd be really grateful if you could submit a PR :D

**Comment by Kinark** [comment]
Fixed in PR #61
