### ISSUE TITLE
Disabling click on step-title

### ISSUE THREAD

**Issue by putrapurba** [Kinark/Materialize-stepper#62]
Hi Igor, I want to disabled click on any step-title so user only navigate by using button, could I make it?

**Comment by Kinark** [comment]
Hey!
It isn't possible right now :(
But it's a nice feature to add as an option. I'll add it in the next version!

**Comment by lacc** [comment]
You can disable it with CSS on the item:
`pointer-events: none;`

**Comment by Kinark** [comment]
Fixed in 3.0.0 release.

**Comment by anuragnagarkota** [comment]
this is not working. Still if i click on step title then it allows me to navigate to that particular step
