### ISSUE TITLE
Event() is not supported in IE.

### ISSUE THREAD

**Issue by pr-github** [Kinark/Materialize-stepper#64]

**Comment by Kinark** [comment]
IE is a pretty old browser that I don't plan to support. The `Event API`, for example, would have to be replaced by [the old way of making events](https://developer.mozilla.org/en-US/docs/Web/API/Event/initEvent), but as the mozilla's site itself said:

> Deprecated
> This feature is no longer recommended. Though some browsers might still support it, it may have already been removed from the relevant web standards, may be in the process of being dropped, or may only be kept for compatibility purposes. Avoid using it, and update existing code if possible; see the compatibility table at the bottom of this page to guide your decision. Be aware that this feature may cease to work at any time.

I believe that IE is a cancer to the world and anyone who uses it should learn that they should stop. It's a fight that we can only win if we stop supporting it. Like Microsoft products? Use Edge.

If you really really need to support it, consider submitting a PR.
