### ISSUE TITLE
Step changed event

### ISSUE THREAD

**Issue by benjaminwols** [Kinark/Materialize-stepper#69]
I use the callback function to execute certain command, but it is not possible to send a callback function when clicking on titles.

Would you be open to a PR which adds a stepchanged event which is fired after the slide animation has taken place?

**Comment by Kinark** [comment]
I'm sorry, I think I didn't understand your question very well :(

The `stepchange` custom event isn't firing when you navigate through the step-titles?

**Comment by Adyllium** [comment]
Hello, 

you can add an event by yourself easily. Check the library and add this lines

![image](https://user-images.githubusercontent.com/87851787/226553019-b86da09f-73c9-4f67-933f-801994ccf93c.png)

![image](https://user-images.githubusercontent.com/87851787/226553176-8f6ffcdc-fea8-4385-8b70-0b657d0bf80a.png)


Just searching for " // !!! Custom new Event " comment to find the new lines
