### ISSUE TITLE
Step line displayed after last step 

### ISSUE THREAD

**Issue by priyankaaravind** [Kinark/Materialize-stepper#7]
Hi, 

1.i am facing problem in step line after last step. i need to activate step dynamically. so i have used activatestep as per documentation.

In my scnario,  initally i have 4 step and some point i will activate new step as 5. 
But initally unwanted line displayed in 4th step (this should be consider as last step no stepper line displayed below)
![image](https://cloud.githubusercontent.com/assets/12719187/24209004/1000ff02-0f4b-11e7-9f9d-944ae4029aad.png)

As per initial level 4 is the final step. so this line should not display. even though added li without .step class and add display none property also this problem occurs. 
After adding 5th step dynamically 5th step doesn't have line like this.

2. Another doubt in data-feedback . if i provide data-feedback option while clicking transparent background apply in that step. i dont want this tranparent background. 

3. i have textbox in step. after focusing and clicking enter key navigates to next stepper in linear stepper. only button click should navigate to nextstep . Please let me know how to disable nextstep and activate nextstep manually.

Hope i conveyed my problem clearly. 
Please help me resolve this.
Thanks in advance.

**Comment by Kinark** [comment]
Hey, Priyanka!

So:

1- It was a bug, fixed in 2.1.1!
2- Added an option for you to disabled it in 2.1.1;
3- It happens because of form spawned around the stepper. I added another option for you to disabled it :)

Thank you for using the stepper!
