### ISSUE TITLE
Customize step count (eg: reverse chronological)

### ISSUE THREAD

**Issue by socket-var** [Kinark/Materialize-stepper#71]
Hi, is there any way I can customize the step counts like display step counts in reverse chronological order. I am making a vertical timeline in reverse chronological order using this package. Haven't seen any options for this in the docs afaik. If this is not possible, are there any alternate components / packages in materialize css that I can leverage for the vertical timeline ?

**Comment by Kinark** [comment]
Sorry, there's no native way to customize the counter. You can read more about the method used to make the counter in here:

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Lists_and_Counters/Using_CSS_counters

I recommend you to use stackoverflow to ask these type of questions. However, I've found this link that could be helpful

http://jsfiddle.net/pN6Fx/

I'm closing this issue for now. Feel free to reopen it if you think I got you wrong or forgot something.

**Comment by socket-var** [comment]
Alright, thanks. I wanted to know if there is an option to do it without custom code. I guess I'll have to override some defaults.
