### ISSUE TITLE
autoFormCreation: false not working

### ISSUE THREAD

**Issue by Mark53CZ** [Kinark/Materialize-stepper#73]
`materialize-stepper.js:591 Uncaught TypeError: Cannot read property 'length' of null
    at materialize-stepper.js:591
    at MStepper._init (materialize-stepper.js:53)
    at new MStepper (materialize-stepper.js:699)`

Browser: Google Chrome 74.0.

I fixed it by changing line 591 from:
`} else if (form.length) {`
to
`else if (form !== undefined && form !== null && form.length) {`

**Comment by Kinark** [comment]
Gonna fix this in the next version.
Thanks.
