### ISSUE TITLE
Stable version - need information

### ISSUE THREAD

**Issue by pglejzer** [Kinark/Materialize-stepper#75]
Hello,
is this information in Readme about stable information is still credible? Is stable version already released? Because this information is giving a little confusing us about a version of what can we use. Thanks!

**Comment by Kinark** [comment]
The last stable version is 3.0.1in both npm and github releases.

Why is it confusing?

**Comment by pglejzer** [comment]
Yea sure but why information about 'not stable version' is still available in the readme? It can give a little misunderstanding about that. Thanks for the information.

**Comment by Kinark** [comment]
You're right, I'll remove the message asap :)

Thanks!

**Comment by Kinark** [comment]
Done
