### ISSUE TITLE
Block the step change by clicking on "step-title"

### ISSUE THREAD

**Issue by Lunok** [Kinark/Materialize-stepper#79]
Hello,

is it possible to have a parameter that prevents the next step by clicking on "step-title" ?

The problem is that in step 2 I give the user the choice to choose a product, depending on the selected product I display dynamic information on the step 3, but step 3 does not receive the dynamic information if the user clicks on "step-title" instead of the "next step" button, the event "data-feedback" is simply not activated.

Thanks

**Comment by Kinark** [comment]
You can use `stepTitleNavigation: false` and the navigation by clicking the `step-title`s will be blocked.

**Comment by Lunok** [comment]
Indeed, sorry for the inconvenience!
