### ISSUE TITLE
resetStepper(); and updateStepper();

### ISSUE THREAD

**Issue by Lunok** [Kinark/Materialize-stepper#80]
Hello, it's me again!

I"d like to make a suggestion about the resetStepper() function, is it possible to reset the titles of the steps with this function ?

All fields are effectively reset and we return to step 1 but the step titles remain visually validated or maybe I missed something ?

The same thing happens on the demo:
https://kinark.github.io/Materialize-stepper/?api_reset_demo_email=rgerger%40hotmail.fr&api_reset_demo_password=sdfsdfsd

Thanks

**Comment by Kinark** [comment]
Yeah, it's a bug :/
I'm gonna fix it in the next version

**Comment by Lunok** [comment]
@Kinark  Hello,
I'd like to inform you that the "updateStepper()" function returns the error "updateStepper() is not a function". However, it can be used by calling it this way: "instance.updateStepper".

**Comment by Kinark** [comment]
Are you sure? How can it be called just by referencing a variable?

**Comment by Lunok** [comment]
Yes, I use webpack-en encore, I don't know if it can be linked... But the bug is really strange, I don't understand it either! I proceeded exactly as explained on the documentation. In the evening, I will create an empty html page and put the stepper on it, it will help to see if the bug happens again, I'll keep you informed.

**Comment by Kinark** [comment]
Thanks for helping me debugging :D

**Comment by Lunok** [comment]
Sorry for the late answer. I've tested the resetStepper() function with just a simple html page and it works perfectly, so i think the problem is caused by the webpack-encore, I'll investigate further to find the problem. For the moment, I'm on vacation, I'll try again when I get back ;D

**Comment by Kinark** [comment]
No problem!
Thanks for using MStepper :D
