### ISSUE TITLE
Remove the effect when a new step appears : "activateStep()"

### ISSUE THREAD

**Issue by Lunok** [Kinark/Materialize-stepper#81]
Hello all,

Is it possible to remove the transition effect when adding a new step dynamically with instance.activateStep() ?

I may have played with the css and the transition attribute, I can't remove it completely, if I do, I have a display bug!

Thank you for your help.

**Comment by Kinark** [comment]
Unfortunately there's no way to remove the transition effect, Lunok, I'm sorry. It'd mess up with the internal logic with the stepper that was built to have smooth transitions everywhere.

**Comment by Lunok** [comment]
All right, thank you for your answer, I'll try to do it differently.
