### ISSUE TITLE
Automatic Height 

### ISSUE THREAD

**Issue by rick2ricks** [Kinark/Materialize-stepper#9]
Any chances in adding this feature ?

**Comment by Kinark** [comment]
You're probably talking about the automatic height on horizontal steppers.

Well, I'll probably add, but I'll have to do it with JS, since it's a little messy keep such different layouts (vertical and horizontal) with the same code.

But I'll try :)

**Comment by akafaneh** [comment]
@Kinark anytime near?

**Comment by tjbarber** [comment]
Yeah, bumping this. Any progress made?

**Comment by elhak** [comment]
no update for this?

**Comment by Loxyz** [comment]
Hey, i've got something working for this issue, if anyone still need it : 

`function resizeStepper() {
    newHeight = 0;
    padding   = 200;

    $('#stepper').find('.step.active').find('.step-content > div').each(function()
    {
        newHeight += parseInt($(this).css('height'));
    });

    newHeight += padding;

    $('#stepper').animate({
            height: newHeight},
        300);
}`

I am calling this function like this :

`        $('#stepper').on('stepchange', function()
        {
            resizeStepper();
        });`

**Comment by RobertThwaite** [comment]
I have done a pull request with automatic height.

**Comment by atul-ui-developer** [comment]
Collapsible is not working well with this code   can help me to fix this height is not detecting on collapsible open

**Comment by atul-ui-developer** [comment]
@Kinark  any time near bro

**Comment by Kinark** [comment]
Hey guys, I'm sorry for the late, laaaaate answer, but the plugin was rewritten from scratch, so I believe anything in this issue is current.

It sill doesn't have automatic height, I'll maybe make it someday, but till then, fell free to submit a PR or a workaround :)

**Comment by Kinark** [comment]
I'm closing this issue for now cause even tho it's on the plans, those plans are future plans.
Thanks for being using MStepper!

**Comment by RonaldoVasques** [comment]
@Loxyz , You helped me out of Monday's mess.. Thanks!

**Comment by ondiekisteve** [comment]
Use CSS to make the height auto.
Use the code below.

ul.stepper.horizontal .step .step-content .step-actions{
    position: absolute !important;
    bottom:auto !important;
    left: auto !important;
}

**Comment by Ronald9919** [comment]
> Use CSS to make the height auto.
> Use the code below.
> 
> ul.stepper.horizontal .step .step-content .step-actions{
> position: absolute !important;
> bottom:auto !important;
> left: auto !important;
> }

Love u
